server:
  port: 8082

spring:
  application:
    name: payment-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999}

  # ===========================
  # Kafka Configuration
  # ===========================
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost


#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always


  security:
    user:
      name: user
      password: password
