package ci.trabrouss.authservice.contract.response;

import lombok.Getter;

@Getter
public enum ErrorCode {
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    BAD_REQUEST("BAD_REQUEST"),
    RESOURCE_ALREADY_EXISTS("RESOURCE_ALREADY_EXISTS"),
    MISSING_FIELD("MISSING_FIELD"),
    INVALID_TYPE("INVALID_TYPE"),
    ACCESS_DENIED("ACCESS_DENIED"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    UNPROCESSABLE_ENTITY("UNPROCESSABLE_ENTITY"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    NOT_ACCEPTABLE("NOT_ACCEPTABLE"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    GATEWAY_TIMEOUT("GATEWAY_TIMEOUT"),
    TOKEN_EXPIRED_ERROR("TOKEN_EXPIRED_ERROR"),
    TOKEN_INVALID_ERROR("TOKEN_INVALID_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }


}
